-- AlterTable
ALTER TABLE "TagType" ALTER COLUMN "tagName" SET NOT NULL,
ALTER COLUMN "tagName" SET DATA TYPE TEXT,
ALTER COLUMN "tagContent" SET NOT NULL,
ALTER COLUMN "tagContent" SET DATA TYPE TEXT;
